const patternList = [
  {
    pattern: "\\d{10}",
    displayText: "D10",
  },
  {
    pattern: "\\d{11}",
    displayText: "D11",
  },
  {
    pattern: "\\d{12}",
    displayText: "D12",
  },
  {
    pattern: "\\d{5} \\d{5}",
    displayText: "D5 SPACE D5",
  },
  {
    pattern: "\\d{5}  \\d{5}",
    displayText: "D5 SPACE SPACE D5",
  },
  {
    pattern: "\\d{7} \\d{3}",
    displayText: "D7 SPACE D3",
  },
  {
    pattern: "\\d{7}-\\d{3}",
    displayText: "D7 - D3",
  },
  {
    pattern: "\\d{3} \\d{4} \\d{3}",
    displayText: "D3 SPACE D4 SPACE D3",
  },
  {
    pattern: "\\d{4} \\d{3} \\d{3}",
    displayText: "D4 SPACE D3 SPACE D3",
  },
  {
    pattern: "\\d{3} \\d{3} \\d{4}",
    displayText: "D3 SPACE D3 SPACE D4",
  },
  {
    pattern: "\\d{2} \\d{2} \\d{2} \\d{2} \\d{2}",
    displayText: "D2 SPACE D2 SPACE D2 SPACE D2 SPACE D2",
  },
  {
    pattern: "\\d{4} \\d{2} \\d{2} \\d{2}",
    displayText: "D4 SPACE D2 SPACE D2 SPACE D2",
  },
  {
    pattern: "\\d{2} \\d{4} \\d{4}",
    displayText: "D2 SPACE D4 SPACE D4",
  },
  {
    pattern: "\\d{3} \\d{2} \\d{2} \\d{3}",
    displayText: "D3 SPACE D2 SPACE D2 SPACE D3",
  },
  {
    pattern: "\\d{2} \\d{2} \\d{2} \\d{4}",
    displayText: "D2 SPACE D2 SPACE D2 SPACE D4",
  },
  {
    pattern: "\\d{4} \\d{4} \\d{2}",
    displayText: "D4 SPACE D4 SPACE D2",
  },
  {
    pattern: "\\d{8} \\d{2}",
    displayText: "D8 SPACE D2",
  },
  {
    pattern: "\\d{2} \\d{8}",
    displayText: "D2 SPACE D8",
  },
  {
    pattern: "\\d{4} \\d{2} \\d{4}",
    displayText: "D4 SPACE D2 SPACE D4",
  },
  {
    pattern: "\\d{4} \\d{6}",
    displayText: "D4 SPACE D6",
  },
  {
    pattern: "\\d{6} \\d{4}",
    displayText: "D6 SPACE D4",
  },
  {
    pattern: "\\d{3} \\d{3} \\d{3} \\d{1}",
    displayText: "D3 SPACE D3 SPACE D3 SPACE D1",
  },
  {
    pattern: "\\d{1} \\d{3} \\d{3} \\d{3}",
    displayText: "D1 SPACE D3 SPACE D3 SPACE D3",
  },
  {
    pattern: "\\d{1} \\d{1} \\d{1} \\d{1} \\d{1} \\d{1} \\d{1} \\d{1} \\d{1} \\d{1}",
    displayText: "D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1 SPACE D1",
  },
];
const cleanupList = [
  {
    originalText: "S",
    replaceText: 5,
  },
  {
    originalText: "�",
    replaceText: "",
  },
  {
    originalText: "O",
    replaceText: 0,
  },
  {
    originalText: "l",
    replaceText: 1,
  },
  {
    originalText: "%",
    replaceText: 8,
  },
];

const resultSettings = {
  predictProviderName: true,
  autoGenerateNumbers: true,
  autoGenerateDigits: 2,
  removeResultsFromInput:false,
};
